# Excluded in GitHub Actions

package:
  name: jj
  version: "0.41.0"
  epoch: 0
  description: "A Git-compatible VCS that is both simple and powerful."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - "https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
    repositories:
      - "https://packages.wolfi.dev/os"
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust-1.95

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jj-vcs/jj
      expected-commit: 413f539283e5a87f0a2c64dec54a5258a1bee78f
      tag: v${{package.version}}
  
  - uses: cargo/build
    with:
      output: jj

  - uses: strip

update:
  enabled: true
  github:
    identifier: jj-vcs/jj
    strip-prefix: v

test:
  pipeline:
    - runs: |
        jj --version
