name: toolbx

on:
  schedule:
    - cron: "01 00 * * 6" # 00:01 every Saturday UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Versions
        id: tag-versions
        run: |
          date +"year=%Y" >> $GITHUB_OUTPUT
          date +"week=%U" >> $GITHUB_OUTPUT
          date +"tag=%Yw%U-${{ github.sha }}" >> $GITHUB_OUTPUT

          packages=$(cat packages/* | sha256sum)
          echo "packages_sum=$packages" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: Build with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: |
            git-${{ github.sha }}
            packages-${{ steps.tag-versions.outputs.packages_sum }}
            ${{ steps.tag-versions.outputs.year }}
            ${{ steps.tag-versions.outputs.tag }}
          containerfiles: |
            ./Containerfile
          build-args: |
            VERSION=${{ github.sha }}
      - name: Push to GitHub Container Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
