name: toolbx

on:
  schedule:
    - cron: "01 00 * * 6" # 00:01 every Saturday UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: tag-version
        runs: |
          date +"year=%Y" >> $GITHUB_OUTPUT
          date +"week=%U" >> $GITHUB_OUTPUT
          date +"tag=Y%YW%U-${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Build with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: git-${{ github.sha }} Y${{ steps.tag-version.year }} ${{ steps.tag-version.tag }}
          containerfiles: |
            ./Containerfile
          build-args: |
            version=${{ github.sha }}
      - name: Push to GitHub Container Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        permissions:
          packages: write
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
