name: toolbx

on:
  schedule:
    - cron: "01 00 * * 6" # 00:01 every Saturday UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: namespace-profile-default
    steps:
      - uses: actions/checkout@v4

      - name: Setup workspace
        id: setup
        run: |
          # Pre-create output directory
          mkdir -p dist/packages

          # Populate packages
          configs=$(ls melange/*.yaml | xargs | tr ' ' ',')
          echo "multi_config=$configs" >> $GITHUB_OUTPUT

          # Version
          date --utc +"release_week=%Yw%U" >> $GITHUB_OUTPUT
          date --utc +"tag=%Yw%U-${{ github.sha }}" >> $GITHUB_OUTPUT

      - uses: chainguard-dev/actions/melange-build@main
        with:
          archs: x86_64,aarch64
          multi-config: ${{ steps.setup.outputs.multi_config }}
          sign-with-temporary-key: true
          repository-path: dist/packages
          git-commit: ${{ github.sha }}
          git-repo-url: github.com/${{ github.repository }}

      - uses: chainguard-images/actions/apko-publish@main
        with:
          archs: x86_64,aarch64
          tag: ghcr.io/${{ github.repository }}:${{ steps.setup.outputs.tag }}
          keyring-append: melange.rsa.pub

      - name: Setup crane
        uses: imjasonh/setup-crane@v0.4

      - name: Re-tag image with latest
        run: |
          crane tag ghcr.io/${{ github.repository }}:${{ steps.setup.outputs.tag }} latest
